CREATE DATABASE flixnet;

CREATE TABLE flixnet.tvShow(
id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(150) NOT NULL
);

CREATE TABLE flixnet.theme(
id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

CREATE TABLE flixnet.tvshow_theme(
tvshow_id TINYINT UNSIGNED NOT NULL,
FOREIGN KEY(tvshow_id) REFERENCES flixnet.tvShow(id),
theme_id TINYINT UNSIGNED NOT NULL,
FOREIGN KEY(theme_id) REFERENCES flixnet.theme(id)   
);

CREATE TABLE flixnet.season(
id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
number VARCHAR(10) NOT NULL,
tvshow_id TINYINT UNSIGNED NOT NULL,
FOREIGN KEY(tvshow_id) REFERENCES flixnet.tvShow(id)
);

CREATE TABLE flixnet.episode(
id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(150) NOT NULL,
number VARCHAR(90) NOT NULL,
duration VARCHAR(100) NOT NULL,
season_id TINYINT UNSIGNED NOT NULL,
FOREIGN KEY(season_id) REFERENCES flixnet.season(id)
);